In [31]:
import numpy as np

NumPy program to create an array of all even integers from 30 to 70

In [32]:
arr = np.arange(30, 71, 2)
print("Array of all even integers from 30 to 70:", arr)

Array of all even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


NumPy program to generate an array of 15 random numbers from a standard normal
distribution

In [33]:
arr = np.random.randn(15)
print("Array of 15 random numbers from a standard normal distribution:", arr)

Array of 15 random numbers from a standard normal distribution: [-0.51742763  1.09975478 -1.07230568 -0.53333584  2.45735845  1.36753245
  1.55388605 -0.59533688 -1.0967582   1.18326009 -1.30848988 -1.82294263
  0.05478838  0.98759457  0.08752768]


Compute the cross-product of two matrices in NumPy

In [34]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[7, 8, 9], [10, 11, 12]])
cross_product = np.cross(m1, m2)
print("Cross-product of two matrices:", cross_product)

Cross-product of two matrices: [[-6 12 -6]
 [-6 12 -6]]


 Compute the determinant of an array using NumPy

In [35]:
arr = np.array([[1, 2], [3, 4]])
dt = np.linalg.det(arr)
print("Determinant of the array:", dt)

Determinant of the array: -2.0000000000000004


3x3x3 array with random values using NumPy

In [36]:
arr = np.random.random((3, 3, 3))
print("3x3x3 array with random values:", arr)

3x3x3 array with random values: [[[0.82619521 0.70398052 0.39727321]
  [0.55442186 0.3413868  0.69210645]
  [0.71900715 0.27462662 0.236485  ]]

 [[0.11018552 0.98582906 0.79067934]
  [0.68980167 0.83405951 0.93479743]
  [0.50701557 0.90889292 0.44629572]]

 [[0.41393882 0.62397618 0.47828196]
  [0.01679504 0.99582987 0.37706687]
  [0.41860828 0.9400675  0.92012108]]]


5x5 array with random values and find the minimum and maximum values using
NumPy

In [37]:
arr = np.random.random((5, 5))
min = np.min(arr)
max = np.max(arr)
print("5x5 array with random values:", arr)
print("Minimum value:", min)
print("Maximum value:", max)

5x5 array with random values: [[0.68651338 0.84801124 0.4985999  0.22888048 0.40525696]
 [0.07654009 0.8212965  0.19349078 0.72504454 0.17004394]
 [0.39219448 0.62177385 0.00911576 0.21524963 0.66201924]
 [0.75692729 0.4386372  0.208292   0.18847801 0.001321  ]
 [0.41905586 0.5824907  0.68770147 0.09214975 0.19621404]]
Minimum value: 0.0013209989088065477
Maximum value: 0.8480112376764932


Compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy

In [38]:
mean_value = np.mean(arr, axis=1)
std_deviation = np.std(arr, axis=1)
variance = np.var(arr, axis=1)
print("Mean along the second axis:", mean_value)
print("Standard deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)

Mean along the second axis: [0.53345239 0.39728317 0.38007059 0.3187311  0.39552236]
Standard deviation along the second axis: [0.21577199 0.31088903 0.24610402 0.25934734 0.22478361]
Variance along the second axis: [0.04655755 0.09665199 0.06056719 0.06726104 0.05052767]
